#include <AST.h>
#include <Sources.h>
#include <CppParser.h>
#include <new>

extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_NativeLibrary_NativeLibrary___1__N_CppSharp_N_CppParser_N_AST_S_NativeLibrary(void* __instance, const CppSharp::CppParser::AST::NativeLibrary& _0) { ::new (__instance) CppSharp::CppParser::AST::NativeLibrary(_0); }
CppSharp::CppParser::AST::NativeLibrary& (CppSharp::CppParser::AST::NativeLibrary::*_0)(const CppSharp::CppParser::AST::NativeLibrary&) = &CppSharp::CppParser::AST::NativeLibrary::operator=;
CppSharp::CppParser::AST::Comment& (CppSharp::CppParser::AST::Comment::*_1)(CppSharp::CppParser::AST::Comment&&) = &CppSharp::CppParser::AST::Comment::operator=;
CppSharp::CppParser::AST::BlockContentComment& (CppSharp::CppParser::AST::BlockContentComment::*_2)(CppSharp::CppParser::AST::BlockContentComment&&) = &CppSharp::CppParser::AST::BlockContentComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_FullComment_FullComment___1__N_CppSharp_N_CppParser_N_AST_S_FullComment(void* __instance, const CppSharp::CppParser::AST::FullComment& _0) { ::new (__instance) CppSharp::CppParser::AST::FullComment(_0); }
CppSharp::CppParser::AST::FullComment& (CppSharp::CppParser::AST::FullComment::*_3)(const CppSharp::CppParser::AST::FullComment&) = &CppSharp::CppParser::AST::FullComment::operator=;
CppSharp::CppParser::AST::InlineContentComment& (CppSharp::CppParser::AST::InlineContentComment::*_4)(CppSharp::CppParser::AST::InlineContentComment&&) = &CppSharp::CppParser::AST::InlineContentComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ParagraphComment_ParagraphComment___1__N_CppSharp_N_CppParser_N_AST_S_ParagraphComment(void* __instance, const CppSharp::CppParser::AST::ParagraphComment& _0) { ::new (__instance) CppSharp::CppParser::AST::ParagraphComment(_0); }
CppSharp::CppParser::AST::ParagraphComment& (CppSharp::CppParser::AST::ParagraphComment::*_5)(const CppSharp::CppParser::AST::ParagraphComment&) = &CppSharp::CppParser::AST::ParagraphComment::operator=;
CppSharp::CppParser::AST::BlockCommandComment::Argument& (CppSharp::CppParser::AST::BlockCommandComment::Argument::*_6)(const CppSharp::CppParser::AST::BlockCommandComment::Argument&) = &CppSharp::CppParser::AST::BlockCommandComment::Argument::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BlockCommandComment_S_Argument__Argument(CppSharp::CppParser::AST::BlockCommandComment::Argument*__instance) { __instance->~Argument(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BlockCommandComment_BlockCommandComment___1__N_CppSharp_N_CppParser_N_AST_S_BlockCommandComment(void* __instance, const CppSharp::CppParser::AST::BlockCommandComment& _0) { ::new (__instance) CppSharp::CppParser::AST::BlockCommandComment(_0); }
CppSharp::CppParser::AST::BlockCommandComment& (CppSharp::CppParser::AST::BlockCommandComment::*_7)(const CppSharp::CppParser::AST::BlockCommandComment&) = &CppSharp::CppParser::AST::BlockCommandComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ParamCommandComment_ParamCommandComment___1__N_CppSharp_N_CppParser_N_AST_S_ParamCommandComment(void* __instance, const CppSharp::CppParser::AST::ParamCommandComment& _0) { ::new (__instance) CppSharp::CppParser::AST::ParamCommandComment(_0); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ParamCommandComment__ParamCommandComment(CppSharp::CppParser::AST::ParamCommandComment*__instance) { __instance->~ParamCommandComment(); }
CppSharp::CppParser::AST::ParamCommandComment& (CppSharp::CppParser::AST::ParamCommandComment::*_8)(const CppSharp::CppParser::AST::ParamCommandComment&) = &CppSharp::CppParser::AST::ParamCommandComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TParamCommandComment_TParamCommandComment___1__N_CppSharp_N_CppParser_N_AST_S_TParamCommandComment(void* __instance, const CppSharp::CppParser::AST::TParamCommandComment& _0) { ::new (__instance) CppSharp::CppParser::AST::TParamCommandComment(_0); }
CppSharp::CppParser::AST::TParamCommandComment& (CppSharp::CppParser::AST::TParamCommandComment::*_9)(CppSharp::CppParser::AST::TParamCommandComment&&) = &CppSharp::CppParser::AST::TParamCommandComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TParamCommandComment__TParamCommandComment(CppSharp::CppParser::AST::TParamCommandComment*__instance) { __instance->~TParamCommandComment(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VerbatimBlockLineComment_VerbatimBlockLineComment___1__N_CppSharp_N_CppParser_N_AST_S_VerbatimBlockLineComment(void* __instance, const CppSharp::CppParser::AST::VerbatimBlockLineComment& _0) { ::new (__instance) CppSharp::CppParser::AST::VerbatimBlockLineComment(_0); }
CppSharp::CppParser::AST::VerbatimBlockLineComment& (CppSharp::CppParser::AST::VerbatimBlockLineComment::*_10)(CppSharp::CppParser::AST::VerbatimBlockLineComment&&) = &CppSharp::CppParser::AST::VerbatimBlockLineComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VerbatimBlockLineComment__VerbatimBlockLineComment(CppSharp::CppParser::AST::VerbatimBlockLineComment*__instance) { __instance->~VerbatimBlockLineComment(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VerbatimBlockComment_VerbatimBlockComment___1__N_CppSharp_N_CppParser_N_AST_S_VerbatimBlockComment(void* __instance, const CppSharp::CppParser::AST::VerbatimBlockComment& _0) { ::new (__instance) CppSharp::CppParser::AST::VerbatimBlockComment(_0); }
CppSharp::CppParser::AST::VerbatimBlockComment& (CppSharp::CppParser::AST::VerbatimBlockComment::*_11)(const CppSharp::CppParser::AST::VerbatimBlockComment&) = &CppSharp::CppParser::AST::VerbatimBlockComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VerbatimLineComment_VerbatimLineComment___1__N_CppSharp_N_CppParser_N_AST_S_VerbatimLineComment(void* __instance, const CppSharp::CppParser::AST::VerbatimLineComment& _0) { ::new (__instance) CppSharp::CppParser::AST::VerbatimLineComment(_0); }
CppSharp::CppParser::AST::VerbatimLineComment& (CppSharp::CppParser::AST::VerbatimLineComment::*_12)(CppSharp::CppParser::AST::VerbatimLineComment&&) = &CppSharp::CppParser::AST::VerbatimLineComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VerbatimLineComment__VerbatimLineComment(CppSharp::CppParser::AST::VerbatimLineComment*__instance) { __instance->~VerbatimLineComment(); }
CppSharp::CppParser::AST::InlineCommandComment::Argument& (CppSharp::CppParser::AST::InlineCommandComment::Argument::*_13)(const CppSharp::CppParser::AST::InlineCommandComment::Argument&) = &CppSharp::CppParser::AST::InlineCommandComment::Argument::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_InlineCommandComment_S_Argument__Argument(CppSharp::CppParser::AST::InlineCommandComment::Argument*__instance) { __instance->~Argument(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_InlineCommandComment_InlineCommandComment___1__N_CppSharp_N_CppParser_N_AST_S_InlineCommandComment(void* __instance, const CppSharp::CppParser::AST::InlineCommandComment& _0) { ::new (__instance) CppSharp::CppParser::AST::InlineCommandComment(_0); }
CppSharp::CppParser::AST::InlineCommandComment& (CppSharp::CppParser::AST::InlineCommandComment::*_14)(CppSharp::CppParser::AST::InlineCommandComment&&) = &CppSharp::CppParser::AST::InlineCommandComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_InlineCommandComment__InlineCommandComment(CppSharp::CppParser::AST::InlineCommandComment*__instance) { __instance->~InlineCommandComment(); }
CppSharp::CppParser::AST::HTMLTagComment& (CppSharp::CppParser::AST::HTMLTagComment::*_15)(CppSharp::CppParser::AST::HTMLTagComment&&) = &CppSharp::CppParser::AST::HTMLTagComment::operator=;
CppSharp::CppParser::AST::HTMLStartTagComment::Attribute& (CppSharp::CppParser::AST::HTMLStartTagComment::Attribute::*_16)(const CppSharp::CppParser::AST::HTMLStartTagComment::Attribute&) = &CppSharp::CppParser::AST::HTMLStartTagComment::Attribute::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_HTMLStartTagComment_S_Attribute__Attribute(CppSharp::CppParser::AST::HTMLStartTagComment::Attribute*__instance) { __instance->~Attribute(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_HTMLStartTagComment_HTMLStartTagComment___1__N_CppSharp_N_CppParser_N_AST_S_HTMLStartTagComment(void* __instance, const CppSharp::CppParser::AST::HTMLStartTagComment& _0) { ::new (__instance) CppSharp::CppParser::AST::HTMLStartTagComment(_0); }
CppSharp::CppParser::AST::HTMLStartTagComment& (CppSharp::CppParser::AST::HTMLStartTagComment::*_17)(CppSharp::CppParser::AST::HTMLStartTagComment&&) = &CppSharp::CppParser::AST::HTMLStartTagComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_HTMLStartTagComment__HTMLStartTagComment(CppSharp::CppParser::AST::HTMLStartTagComment*__instance) { __instance->~HTMLStartTagComment(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_HTMLEndTagComment_HTMLEndTagComment___1__N_CppSharp_N_CppParser_N_AST_S_HTMLEndTagComment(void* __instance, const CppSharp::CppParser::AST::HTMLEndTagComment& _0) { ::new (__instance) CppSharp::CppParser::AST::HTMLEndTagComment(_0); }
CppSharp::CppParser::AST::HTMLEndTagComment& (CppSharp::CppParser::AST::HTMLEndTagComment::*_18)(CppSharp::CppParser::AST::HTMLEndTagComment&&) = &CppSharp::CppParser::AST::HTMLEndTagComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_HTMLEndTagComment__HTMLEndTagComment(CppSharp::CppParser::AST::HTMLEndTagComment*__instance) { __instance->~HTMLEndTagComment(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TextComment_TextComment___1__N_CppSharp_N_CppParser_N_AST_S_TextComment(void* __instance, const CppSharp::CppParser::AST::TextComment& _0) { ::new (__instance) CppSharp::CppParser::AST::TextComment(_0); }
CppSharp::CppParser::AST::TextComment& (CppSharp::CppParser::AST::TextComment::*_19)(CppSharp::CppParser::AST::TextComment&&) = &CppSharp::CppParser::AST::TextComment::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TextComment__TextComment(CppSharp::CppParser::AST::TextComment*__instance) { __instance->~TextComment(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_RawComment_RawComment___1__N_CppSharp_N_CppParser_N_AST_S_RawComment(void* __instance, const CppSharp::CppParser::AST::RawComment& _0) { ::new (__instance) CppSharp::CppParser::AST::RawComment(_0); }
CppSharp::CppParser::AST::RawComment& (CppSharp::CppParser::AST::RawComment::*_20)(const CppSharp::CppParser::AST::RawComment&) = &CppSharp::CppParser::AST::RawComment::operator=;
CppSharp::CppParser::SourceLocation& (CppSharp::CppParser::SourceLocation::*_21)(CppSharp::CppParser::SourceLocation&&) = &CppSharp::CppParser::SourceLocation::operator=;
CppSharp::CppParser::SourceRange& (CppSharp::CppParser::SourceRange::*_22)(CppSharp::CppParser::SourceRange&&) = &CppSharp::CppParser::SourceRange::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_S_SourceRange_SourceRange(void* __instance) { ::new (__instance) CppSharp::CppParser::SourceRange(); }
CppSharp::CppParser::AST::Type& (CppSharp::CppParser::AST::Type::*_23)(const CppSharp::CppParser::AST::Type&) = &CppSharp::CppParser::AST::Type::operator=;
CppSharp::CppParser::AST::TypeQualifiers& (CppSharp::CppParser::AST::TypeQualifiers::*_24)(CppSharp::CppParser::AST::TypeQualifiers&&) = &CppSharp::CppParser::AST::TypeQualifiers::operator=;
CppSharp::CppParser::AST::QualifiedType& (CppSharp::CppParser::AST::QualifiedType::*_25)(CppSharp::CppParser::AST::QualifiedType&&) = &CppSharp::CppParser::AST::QualifiedType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TagType_TagType___1__N_CppSharp_N_CppParser_N_AST_S_TagType(void* __instance, const CppSharp::CppParser::AST::TagType& _0) { ::new (__instance) CppSharp::CppParser::AST::TagType(_0); }
CppSharp::CppParser::AST::TagType& (CppSharp::CppParser::AST::TagType::*_26)(const CppSharp::CppParser::AST::TagType&) = &CppSharp::CppParser::AST::TagType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ArrayType_ArrayType___1__N_CppSharp_N_CppParser_N_AST_S_ArrayType(void* __instance, const CppSharp::CppParser::AST::ArrayType& _0) { ::new (__instance) CppSharp::CppParser::AST::ArrayType(_0); }
CppSharp::CppParser::AST::ArrayType& (CppSharp::CppParser::AST::ArrayType::*_27)(const CppSharp::CppParser::AST::ArrayType&) = &CppSharp::CppParser::AST::ArrayType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_FunctionType_FunctionType___1__N_CppSharp_N_CppParser_N_AST_S_FunctionType(void* __instance, const CppSharp::CppParser::AST::FunctionType& _0) { ::new (__instance) CppSharp::CppParser::AST::FunctionType(_0); }
CppSharp::CppParser::AST::FunctionType& (CppSharp::CppParser::AST::FunctionType::*_28)(const CppSharp::CppParser::AST::FunctionType&) = &CppSharp::CppParser::AST::FunctionType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_PointerType_PointerType___1__N_CppSharp_N_CppParser_N_AST_S_PointerType(void* __instance, const CppSharp::CppParser::AST::PointerType& _0) { ::new (__instance) CppSharp::CppParser::AST::PointerType(_0); }
CppSharp::CppParser::AST::PointerType& (CppSharp::CppParser::AST::PointerType::*_29)(const CppSharp::CppParser::AST::PointerType&) = &CppSharp::CppParser::AST::PointerType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_MemberPointerType_MemberPointerType___1__N_CppSharp_N_CppParser_N_AST_S_MemberPointerType(void* __instance, const CppSharp::CppParser::AST::MemberPointerType& _0) { ::new (__instance) CppSharp::CppParser::AST::MemberPointerType(_0); }
CppSharp::CppParser::AST::MemberPointerType& (CppSharp::CppParser::AST::MemberPointerType::*_30)(const CppSharp::CppParser::AST::MemberPointerType&) = &CppSharp::CppParser::AST::MemberPointerType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TypedefType_TypedefType___1__N_CppSharp_N_CppParser_N_AST_S_TypedefType(void* __instance, const CppSharp::CppParser::AST::TypedefType& _0) { ::new (__instance) CppSharp::CppParser::AST::TypedefType(_0); }
CppSharp::CppParser::AST::TypedefType& (CppSharp::CppParser::AST::TypedefType::*_31)(const CppSharp::CppParser::AST::TypedefType&) = &CppSharp::CppParser::AST::TypedefType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_AttributedType_AttributedType___1__N_CppSharp_N_CppParser_N_AST_S_AttributedType(void* __instance, const CppSharp::CppParser::AST::AttributedType& _0) { ::new (__instance) CppSharp::CppParser::AST::AttributedType(_0); }
CppSharp::CppParser::AST::AttributedType& (CppSharp::CppParser::AST::AttributedType::*_32)(const CppSharp::CppParser::AST::AttributedType&) = &CppSharp::CppParser::AST::AttributedType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DecayedType_DecayedType___1__N_CppSharp_N_CppParser_N_AST_S_DecayedType(void* __instance, const CppSharp::CppParser::AST::DecayedType& _0) { ::new (__instance) CppSharp::CppParser::AST::DecayedType(_0); }
CppSharp::CppParser::AST::DecayedType& (CppSharp::CppParser::AST::DecayedType::*_33)(const CppSharp::CppParser::AST::DecayedType&) = &CppSharp::CppParser::AST::DecayedType::operator=;
CppSharp::CppParser::AST::TemplateArgument& (CppSharp::CppParser::AST::TemplateArgument::*_34)(CppSharp::CppParser::AST::TemplateArgument&&) = &CppSharp::CppParser::AST::TemplateArgument::operator=;
CppSharp::CppParser::AST::TemplateSpecializationType& (CppSharp::CppParser::AST::TemplateSpecializationType::*_35)(const CppSharp::CppParser::AST::TemplateSpecializationType&) = &CppSharp::CppParser::AST::TemplateSpecializationType::operator=;
CppSharp::CppParser::AST::DependentTemplateSpecializationType& (CppSharp::CppParser::AST::DependentTemplateSpecializationType::*_36)(const CppSharp::CppParser::AST::DependentTemplateSpecializationType&) = &CppSharp::CppParser::AST::DependentTemplateSpecializationType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TemplateParameterType_TemplateParameterType___1__N_CppSharp_N_CppParser_N_AST_S_TemplateParameterType(void* __instance, const CppSharp::CppParser::AST::TemplateParameterType& _0) { ::new (__instance) CppSharp::CppParser::AST::TemplateParameterType(_0); }
CppSharp::CppParser::AST::TemplateParameterType& (CppSharp::CppParser::AST::TemplateParameterType::*_37)(const CppSharp::CppParser::AST::TemplateParameterType&) = &CppSharp::CppParser::AST::TemplateParameterType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TemplateParameterSubstitutionType_TemplateParameterSubstitutionType___1__N_CppSharp_N_CppParser_N_AST_S_TemplateParameterSubstitutionType(void* __instance, const CppSharp::CppParser::AST::TemplateParameterSubstitutionType& _0) { ::new (__instance) CppSharp::CppParser::AST::TemplateParameterSubstitutionType(_0); }
CppSharp::CppParser::AST::TemplateParameterSubstitutionType& (CppSharp::CppParser::AST::TemplateParameterSubstitutionType::*_38)(const CppSharp::CppParser::AST::TemplateParameterSubstitutionType&) = &CppSharp::CppParser::AST::TemplateParameterSubstitutionType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_InjectedClassNameType_InjectedClassNameType___1__N_CppSharp_N_CppParser_N_AST_S_InjectedClassNameType(void* __instance, const CppSharp::CppParser::AST::InjectedClassNameType& _0) { ::new (__instance) CppSharp::CppParser::AST::InjectedClassNameType(_0); }
CppSharp::CppParser::AST::InjectedClassNameType& (CppSharp::CppParser::AST::InjectedClassNameType::*_39)(const CppSharp::CppParser::AST::InjectedClassNameType&) = &CppSharp::CppParser::AST::InjectedClassNameType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DependentNameType_DependentNameType___1__N_CppSharp_N_CppParser_N_AST_S_DependentNameType(void* __instance, const CppSharp::CppParser::AST::DependentNameType& _0) { ::new (__instance) CppSharp::CppParser::AST::DependentNameType(_0); }
CppSharp::CppParser::AST::DependentNameType& (CppSharp::CppParser::AST::DependentNameType::*_40)(const CppSharp::CppParser::AST::DependentNameType&) = &CppSharp::CppParser::AST::DependentNameType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_PackExpansionType_PackExpansionType___1__N_CppSharp_N_CppParser_N_AST_S_PackExpansionType(void* __instance, const CppSharp::CppParser::AST::PackExpansionType& _0) { ::new (__instance) CppSharp::CppParser::AST::PackExpansionType(_0); }
CppSharp::CppParser::AST::PackExpansionType& (CppSharp::CppParser::AST::PackExpansionType::*_41)(const CppSharp::CppParser::AST::PackExpansionType&) = &CppSharp::CppParser::AST::PackExpansionType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_UnaryTransformType_UnaryTransformType___1__N_CppSharp_N_CppParser_N_AST_S_UnaryTransformType(void* __instance, const CppSharp::CppParser::AST::UnaryTransformType& _0) { ::new (__instance) CppSharp::CppParser::AST::UnaryTransformType(_0); }
CppSharp::CppParser::AST::UnaryTransformType& (CppSharp::CppParser::AST::UnaryTransformType::*_42)(const CppSharp::CppParser::AST::UnaryTransformType&) = &CppSharp::CppParser::AST::UnaryTransformType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_UnresolvedUsingType_UnresolvedUsingType___1__N_CppSharp_N_CppParser_N_AST_S_UnresolvedUsingType(void* __instance, const CppSharp::CppParser::AST::UnresolvedUsingType& _0) { ::new (__instance) CppSharp::CppParser::AST::UnresolvedUsingType(_0); }
CppSharp::CppParser::AST::UnresolvedUsingType& (CppSharp::CppParser::AST::UnresolvedUsingType::*_43)(const CppSharp::CppParser::AST::UnresolvedUsingType&) = &CppSharp::CppParser::AST::UnresolvedUsingType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VectorType_VectorType___1__N_CppSharp_N_CppParser_N_AST_S_VectorType(void* __instance, const CppSharp::CppParser::AST::VectorType& _0) { ::new (__instance) CppSharp::CppParser::AST::VectorType(_0); }
CppSharp::CppParser::AST::VectorType& (CppSharp::CppParser::AST::VectorType::*_44)(const CppSharp::CppParser::AST::VectorType&) = &CppSharp::CppParser::AST::VectorType::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BuiltinType_BuiltinType___1__N_CppSharp_N_CppParser_N_AST_S_BuiltinType(void* __instance, const CppSharp::CppParser::AST::BuiltinType& _0) { ::new (__instance) CppSharp::CppParser::AST::BuiltinType(_0); }
CppSharp::CppParser::AST::BuiltinType& (CppSharp::CppParser::AST::BuiltinType::*_45)(const CppSharp::CppParser::AST::BuiltinType&) = &CppSharp::CppParser::AST::BuiltinType::operator=;
CppSharp::CppParser::AST::Declaration& (CppSharp::CppParser::AST::Declaration::*_46)(const CppSharp::CppParser::AST::Declaration&) = &CppSharp::CppParser::AST::Declaration::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DeclarationContext_DeclarationContext___1__N_CppSharp_N_CppParser_N_AST_S_DeclarationContext(void* __instance, const CppSharp::CppParser::AST::DeclarationContext& _0) { ::new (__instance) CppSharp::CppParser::AST::DeclarationContext(_0); }
CppSharp::CppParser::AST::DeclarationContext& (CppSharp::CppParser::AST::DeclarationContext::*_47)(CppSharp::CppParser::AST::DeclarationContext&&) = &CppSharp::CppParser::AST::DeclarationContext::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DeclarationContext__DeclarationContext(CppSharp::CppParser::AST::DeclarationContext*__instance) { __instance->~DeclarationContext(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TypedefNameDecl_TypedefNameDecl___1__N_CppSharp_N_CppParser_N_AST_S_TypedefNameDecl(void* __instance, const CppSharp::CppParser::AST::TypedefNameDecl& _0) { ::new (__instance) CppSharp::CppParser::AST::TypedefNameDecl(_0); }
CppSharp::CppParser::AST::TypedefNameDecl& (CppSharp::CppParser::AST::TypedefNameDecl::*_48)(const CppSharp::CppParser::AST::TypedefNameDecl&) = &CppSharp::CppParser::AST::TypedefNameDecl::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TypedefDecl_TypedefDecl___1__N_CppSharp_N_CppParser_N_AST_S_TypedefDecl(void* __instance, const CppSharp::CppParser::AST::TypedefDecl& _0) { ::new (__instance) CppSharp::CppParser::AST::TypedefDecl(_0); }
CppSharp::CppParser::AST::TypedefDecl& (CppSharp::CppParser::AST::TypedefDecl::*_49)(const CppSharp::CppParser::AST::TypedefDecl&) = &CppSharp::CppParser::AST::TypedefDecl::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TypeAlias_TypeAlias___1__N_CppSharp_N_CppParser_N_AST_S_TypeAlias(void* __instance, const CppSharp::CppParser::AST::TypeAlias& _0) { ::new (__instance) CppSharp::CppParser::AST::TypeAlias(_0); }
CppSharp::CppParser::AST::TypeAlias& (CppSharp::CppParser::AST::TypeAlias::*_50)(const CppSharp::CppParser::AST::TypeAlias&) = &CppSharp::CppParser::AST::TypeAlias::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Friend_Friend___1__N_CppSharp_N_CppParser_N_AST_S_Friend(void* __instance, const CppSharp::CppParser::AST::Friend& _0) { ::new (__instance) CppSharp::CppParser::AST::Friend(_0); }
CppSharp::CppParser::AST::Friend& (CppSharp::CppParser::AST::Friend::*_51)(const CppSharp::CppParser::AST::Friend&) = &CppSharp::CppParser::AST::Friend::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_StatementObsolete_StatementObsolete___1__N_CppSharp_N_CppParser_N_AST_S_StatementObsolete(void* __instance, const CppSharp::CppParser::AST::StatementObsolete& _0) { ::new (__instance) CppSharp::CppParser::AST::StatementObsolete(_0); }
CppSharp::CppParser::AST::StatementObsolete& (CppSharp::CppParser::AST::StatementObsolete::*_52)(CppSharp::CppParser::AST::StatementObsolete&&) = &CppSharp::CppParser::AST::StatementObsolete::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_StatementObsolete__StatementObsolete(CppSharp::CppParser::AST::StatementObsolete*__instance) { __instance->~StatementObsolete(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ExpressionObsolete_ExpressionObsolete___1__N_CppSharp_N_CppParser_N_AST_S_ExpressionObsolete(void* __instance, const CppSharp::CppParser::AST::ExpressionObsolete& _0) { ::new (__instance) CppSharp::CppParser::AST::ExpressionObsolete(_0); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ExpressionObsolete__ExpressionObsolete(CppSharp::CppParser::AST::ExpressionObsolete*__instance) { __instance->~ExpressionObsolete(); }
CppSharp::CppParser::AST::ExpressionObsolete& (CppSharp::CppParser::AST::ExpressionObsolete::*_53)(CppSharp::CppParser::AST::ExpressionObsolete&&) = &CppSharp::CppParser::AST::ExpressionObsolete::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BinaryOperatorObsolete_BinaryOperatorObsolete___1__N_CppSharp_N_CppParser_N_AST_S_BinaryOperatorObsolete(void* __instance, const CppSharp::CppParser::AST::BinaryOperatorObsolete& _0) { ::new (__instance) CppSharp::CppParser::AST::BinaryOperatorObsolete(_0); }
CppSharp::CppParser::AST::BinaryOperatorObsolete& (CppSharp::CppParser::AST::BinaryOperatorObsolete::*_54)(const CppSharp::CppParser::AST::BinaryOperatorObsolete&) = &CppSharp::CppParser::AST::BinaryOperatorObsolete::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CallExprObsolete_CallExprObsolete___1__N_CppSharp_N_CppParser_N_AST_S_CallExprObsolete(void* __instance, const CppSharp::CppParser::AST::CallExprObsolete& _0) { ::new (__instance) CppSharp::CppParser::AST::CallExprObsolete(_0); }
CppSharp::CppParser::AST::CallExprObsolete& (CppSharp::CppParser::AST::CallExprObsolete::*_55)(const CppSharp::CppParser::AST::CallExprObsolete&) = &CppSharp::CppParser::AST::CallExprObsolete::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXConstructExprObsolete_CXXConstructExprObsolete___1__N_CppSharp_N_CppParser_N_AST_S_CXXConstructExprObsolete(void* __instance, const CppSharp::CppParser::AST::CXXConstructExprObsolete& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXConstructExprObsolete(_0); }
CppSharp::CppParser::AST::CXXConstructExprObsolete& (CppSharp::CppParser::AST::CXXConstructExprObsolete::*_56)(const CppSharp::CppParser::AST::CXXConstructExprObsolete&) = &CppSharp::CppParser::AST::CXXConstructExprObsolete::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Parameter_Parameter___1__N_CppSharp_N_CppParser_N_AST_S_Parameter(void* __instance, const CppSharp::CppParser::AST::Parameter& _0) { ::new (__instance) CppSharp::CppParser::AST::Parameter(_0); }
CppSharp::CppParser::AST::Parameter& (CppSharp::CppParser::AST::Parameter::*_57)(const CppSharp::CppParser::AST::Parameter&) = &CppSharp::CppParser::AST::Parameter::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Function_Function___1__N_CppSharp_N_CppParser_N_AST_S_Function(void* __instance, const CppSharp::CppParser::AST::Function& _0) { ::new (__instance) CppSharp::CppParser::AST::Function(_0); }
CppSharp::CppParser::AST::Function& (CppSharp::CppParser::AST::Function::*_58)(const CppSharp::CppParser::AST::Function&) = &CppSharp::CppParser::AST::Function::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Method_Method___1__N_CppSharp_N_CppParser_N_AST_S_Method(void* __instance, const CppSharp::CppParser::AST::Method& _0) { ::new (__instance) CppSharp::CppParser::AST::Method(_0); }
CppSharp::CppParser::AST::Method& (CppSharp::CppParser::AST::Method::*_59)(const CppSharp::CppParser::AST::Method&) = &CppSharp::CppParser::AST::Method::operator=;
CppSharp::CppParser::AST::Enumeration::Item& (CppSharp::CppParser::AST::Enumeration::Item::*_60)(const CppSharp::CppParser::AST::Enumeration::Item&) = &CppSharp::CppParser::AST::Enumeration::Item::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Enumeration_Enumeration___1__N_CppSharp_N_CppParser_N_AST_S_Enumeration(void* __instance, const CppSharp::CppParser::AST::Enumeration& _0) { ::new (__instance) CppSharp::CppParser::AST::Enumeration(_0); }
CppSharp::CppParser::AST::Enumeration& (CppSharp::CppParser::AST::Enumeration::*_61)(const CppSharp::CppParser::AST::Enumeration&) = &CppSharp::CppParser::AST::Enumeration::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Variable_Variable___1__N_CppSharp_N_CppParser_N_AST_S_Variable(void* __instance, const CppSharp::CppParser::AST::Variable& _0) { ::new (__instance) CppSharp::CppParser::AST::Variable(_0); }
CppSharp::CppParser::AST::Variable& (CppSharp::CppParser::AST::Variable::*_62)(const CppSharp::CppParser::AST::Variable&) = &CppSharp::CppParser::AST::Variable::operator=;
CppSharp::CppParser::AST::BaseClassSpecifier& (CppSharp::CppParser::AST::BaseClassSpecifier::*_63)(CppSharp::CppParser::AST::BaseClassSpecifier&&) = &CppSharp::CppParser::AST::BaseClassSpecifier::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Field_Field___1__N_CppSharp_N_CppParser_N_AST_S_Field(void* __instance, const CppSharp::CppParser::AST::Field& _0) { ::new (__instance) CppSharp::CppParser::AST::Field(_0); }
CppSharp::CppParser::AST::Field& (CppSharp::CppParser::AST::Field::*_64)(const CppSharp::CppParser::AST::Field&) = &CppSharp::CppParser::AST::Field::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_AccessSpecifierDecl_AccessSpecifierDecl___1__N_CppSharp_N_CppParser_N_AST_S_AccessSpecifierDecl(void* __instance, const CppSharp::CppParser::AST::AccessSpecifierDecl& _0) { ::new (__instance) CppSharp::CppParser::AST::AccessSpecifierDecl(_0); }
CppSharp::CppParser::AST::AccessSpecifierDecl& (CppSharp::CppParser::AST::AccessSpecifierDecl::*_65)(const CppSharp::CppParser::AST::AccessSpecifierDecl&) = &CppSharp::CppParser::AST::AccessSpecifierDecl::operator=;
CppSharp::CppParser::AST::VTableComponent& (CppSharp::CppParser::AST::VTableComponent::*_66)(CppSharp::CppParser::AST::VTableComponent&&) = &CppSharp::CppParser::AST::VTableComponent::operator=;
CppSharp::CppParser::AST::VTableLayout& (CppSharp::CppParser::AST::VTableLayout::*_67)(const CppSharp::CppParser::AST::VTableLayout&) = &CppSharp::CppParser::AST::VTableLayout::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VFTableInfo__VFTableInfo(CppSharp::CppParser::AST::VFTableInfo*__instance) { __instance->~VFTableInfo(); }
CppSharp::CppParser::AST::VFTableInfo& (CppSharp::CppParser::AST::VFTableInfo::*_68)(const CppSharp::CppParser::AST::VFTableInfo&) = &CppSharp::CppParser::AST::VFTableInfo::operator=;
CppSharp::CppParser::AST::LayoutField& (CppSharp::CppParser::AST::LayoutField::*_69)(const CppSharp::CppParser::AST::LayoutField&) = &CppSharp::CppParser::AST::LayoutField::operator=;
CppSharp::CppParser::AST::LayoutBase& (CppSharp::CppParser::AST::LayoutBase::*_70)(const CppSharp::CppParser::AST::LayoutBase&) = &CppSharp::CppParser::AST::LayoutBase::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ClassLayout_ClassLayout___1__N_CppSharp_N_CppParser_N_AST_S_ClassLayout(void* __instance, const CppSharp::CppParser::AST::ClassLayout& _0) { ::new (__instance) CppSharp::CppParser::AST::ClassLayout(_0); }
CppSharp::CppParser::AST::ClassLayout& (CppSharp::CppParser::AST::ClassLayout::*_71)(CppSharp::CppParser::AST::ClassLayout&&) = &CppSharp::CppParser::AST::ClassLayout::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ClassLayout__ClassLayout(CppSharp::CppParser::AST::ClassLayout*__instance) { __instance->~ClassLayout(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Class_Class___1__N_CppSharp_N_CppParser_N_AST_S_Class(void* __instance, const CppSharp::CppParser::AST::Class& _0) { ::new (__instance) CppSharp::CppParser::AST::Class(_0); }
CppSharp::CppParser::AST::Class& (CppSharp::CppParser::AST::Class::*_72)(const CppSharp::CppParser::AST::Class&) = &CppSharp::CppParser::AST::Class::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Template_Template___1__N_CppSharp_N_CppParser_N_AST_S_Template(void* __instance, const CppSharp::CppParser::AST::Template& _0) { ::new (__instance) CppSharp::CppParser::AST::Template(_0); }
CppSharp::CppParser::AST::Template& (CppSharp::CppParser::AST::Template::*_73)(CppSharp::CppParser::AST::Template&&) = &CppSharp::CppParser::AST::Template::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Template__Template(CppSharp::CppParser::AST::Template*__instance) { __instance->~Template(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TypeAliasTemplate_TypeAliasTemplate___1__N_CppSharp_N_CppParser_N_AST_S_TypeAliasTemplate(void* __instance, const CppSharp::CppParser::AST::TypeAliasTemplate& _0) { ::new (__instance) CppSharp::CppParser::AST::TypeAliasTemplate(_0); }
CppSharp::CppParser::AST::TypeAliasTemplate& (CppSharp::CppParser::AST::TypeAliasTemplate::*_74)(const CppSharp::CppParser::AST::TypeAliasTemplate&) = &CppSharp::CppParser::AST::TypeAliasTemplate::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TemplateParameter_TemplateParameter___1__N_CppSharp_N_CppParser_N_AST_S_TemplateParameter(void* __instance, const CppSharp::CppParser::AST::TemplateParameter& _0) { ::new (__instance) CppSharp::CppParser::AST::TemplateParameter(_0); }
CppSharp::CppParser::AST::TemplateParameter& (CppSharp::CppParser::AST::TemplateParameter::*_75)(const CppSharp::CppParser::AST::TemplateParameter&) = &CppSharp::CppParser::AST::TemplateParameter::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TemplateTemplateParameter_TemplateTemplateParameter___1__N_CppSharp_N_CppParser_N_AST_S_TemplateTemplateParameter(void* __instance, const CppSharp::CppParser::AST::TemplateTemplateParameter& _0) { ::new (__instance) CppSharp::CppParser::AST::TemplateTemplateParameter(_0); }
CppSharp::CppParser::AST::TemplateTemplateParameter& (CppSharp::CppParser::AST::TemplateTemplateParameter::*_76)(const CppSharp::CppParser::AST::TemplateTemplateParameter&) = &CppSharp::CppParser::AST::TemplateTemplateParameter::operator=;
CppSharp::CppParser::AST::TypeTemplateParameter& (CppSharp::CppParser::AST::TypeTemplateParameter::*_77)(const CppSharp::CppParser::AST::TypeTemplateParameter&) = &CppSharp::CppParser::AST::TypeTemplateParameter::operator=;
CppSharp::CppParser::AST::NonTypeTemplateParameter& (CppSharp::CppParser::AST::NonTypeTemplateParameter::*_78)(const CppSharp::CppParser::AST::NonTypeTemplateParameter&) = &CppSharp::CppParser::AST::NonTypeTemplateParameter::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ClassTemplate_ClassTemplate___1__N_CppSharp_N_CppParser_N_AST_S_ClassTemplate(void* __instance, const CppSharp::CppParser::AST::ClassTemplate& _0) { ::new (__instance) CppSharp::CppParser::AST::ClassTemplate(_0); }
CppSharp::CppParser::AST::ClassTemplate& (CppSharp::CppParser::AST::ClassTemplate::*_79)(const CppSharp::CppParser::AST::ClassTemplate&) = &CppSharp::CppParser::AST::ClassTemplate::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ClassTemplateSpecialization_ClassTemplateSpecialization___1__N_CppSharp_N_CppParser_N_AST_S_ClassTemplateSpecialization(void* __instance, const CppSharp::CppParser::AST::ClassTemplateSpecialization& _0) { ::new (__instance) CppSharp::CppParser::AST::ClassTemplateSpecialization(_0); }
CppSharp::CppParser::AST::ClassTemplateSpecialization& (CppSharp::CppParser::AST::ClassTemplateSpecialization::*_80)(const CppSharp::CppParser::AST::ClassTemplateSpecialization&) = &CppSharp::CppParser::AST::ClassTemplateSpecialization::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ClassTemplatePartialSpecialization_ClassTemplatePartialSpecialization___1__N_CppSharp_N_CppParser_N_AST_S_ClassTemplatePartialSpecialization(void* __instance, const CppSharp::CppParser::AST::ClassTemplatePartialSpecialization& _0) { ::new (__instance) CppSharp::CppParser::AST::ClassTemplatePartialSpecialization(_0); }
CppSharp::CppParser::AST::ClassTemplatePartialSpecialization& (CppSharp::CppParser::AST::ClassTemplatePartialSpecialization::*_81)(const CppSharp::CppParser::AST::ClassTemplatePartialSpecialization&) = &CppSharp::CppParser::AST::ClassTemplatePartialSpecialization::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_FunctionTemplate_FunctionTemplate___1__N_CppSharp_N_CppParser_N_AST_S_FunctionTemplate(void* __instance, const CppSharp::CppParser::AST::FunctionTemplate& _0) { ::new (__instance) CppSharp::CppParser::AST::FunctionTemplate(_0); }
CppSharp::CppParser::AST::FunctionTemplate& (CppSharp::CppParser::AST::FunctionTemplate::*_82)(const CppSharp::CppParser::AST::FunctionTemplate&) = &CppSharp::CppParser::AST::FunctionTemplate::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_FunctionTemplateSpecialization_FunctionTemplateSpecialization___1__N_CppSharp_N_CppParser_N_AST_S_FunctionTemplateSpecialization(void* __instance, const CppSharp::CppParser::AST::FunctionTemplateSpecialization& _0) { ::new (__instance) CppSharp::CppParser::AST::FunctionTemplateSpecialization(_0); }
CppSharp::CppParser::AST::FunctionTemplateSpecialization& (CppSharp::CppParser::AST::FunctionTemplateSpecialization::*_83)(const CppSharp::CppParser::AST::FunctionTemplateSpecialization&) = &CppSharp::CppParser::AST::FunctionTemplateSpecialization::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VarTemplate_VarTemplate___1__N_CppSharp_N_CppParser_N_AST_S_VarTemplate(void* __instance, const CppSharp::CppParser::AST::VarTemplate& _0) { ::new (__instance) CppSharp::CppParser::AST::VarTemplate(_0); }
CppSharp::CppParser::AST::VarTemplate& (CppSharp::CppParser::AST::VarTemplate::*_84)(const CppSharp::CppParser::AST::VarTemplate&) = &CppSharp::CppParser::AST::VarTemplate::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VarTemplateSpecialization_VarTemplateSpecialization___1__N_CppSharp_N_CppParser_N_AST_S_VarTemplateSpecialization(void* __instance, const CppSharp::CppParser::AST::VarTemplateSpecialization& _0) { ::new (__instance) CppSharp::CppParser::AST::VarTemplateSpecialization(_0); }
CppSharp::CppParser::AST::VarTemplateSpecialization& (CppSharp::CppParser::AST::VarTemplateSpecialization::*_85)(const CppSharp::CppParser::AST::VarTemplateSpecialization&) = &CppSharp::CppParser::AST::VarTemplateSpecialization::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_VarTemplatePartialSpecialization_VarTemplatePartialSpecialization___1__N_CppSharp_N_CppParser_N_AST_S_VarTemplatePartialSpecialization(void* __instance, const CppSharp::CppParser::AST::VarTemplatePartialSpecialization& _0) { ::new (__instance) CppSharp::CppParser::AST::VarTemplatePartialSpecialization(_0); }
CppSharp::CppParser::AST::VarTemplatePartialSpecialization& (CppSharp::CppParser::AST::VarTemplatePartialSpecialization::*_86)(const CppSharp::CppParser::AST::VarTemplatePartialSpecialization&) = &CppSharp::CppParser::AST::VarTemplatePartialSpecialization::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_UnresolvedUsingTypename_UnresolvedUsingTypename___1__N_CppSharp_N_CppParser_N_AST_S_UnresolvedUsingTypename(void* __instance, const CppSharp::CppParser::AST::UnresolvedUsingTypename& _0) { ::new (__instance) CppSharp::CppParser::AST::UnresolvedUsingTypename(_0); }
CppSharp::CppParser::AST::UnresolvedUsingTypename& (CppSharp::CppParser::AST::UnresolvedUsingTypename::*_87)(const CppSharp::CppParser::AST::UnresolvedUsingTypename&) = &CppSharp::CppParser::AST::UnresolvedUsingTypename::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_Namespace_Namespace___1__N_CppSharp_N_CppParser_N_AST_S_Namespace(void* __instance, const CppSharp::CppParser::AST::Namespace& _0) { ::new (__instance) CppSharp::CppParser::AST::Namespace(_0); }
CppSharp::CppParser::AST::Namespace& (CppSharp::CppParser::AST::Namespace::*_88)(const CppSharp::CppParser::AST::Namespace&) = &CppSharp::CppParser::AST::Namespace::operator=;
CppSharp::CppParser::AST::PreprocessedEntity& (CppSharp::CppParser::AST::PreprocessedEntity::*_89)(CppSharp::CppParser::AST::PreprocessedEntity&&) = &CppSharp::CppParser::AST::PreprocessedEntity::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_MacroDefinition_MacroDefinition___1__N_CppSharp_N_CppParser_N_AST_S_MacroDefinition(void* __instance, const CppSharp::CppParser::AST::MacroDefinition& _0) { ::new (__instance) CppSharp::CppParser::AST::MacroDefinition(_0); }
CppSharp::CppParser::AST::MacroDefinition& (CppSharp::CppParser::AST::MacroDefinition::*_90)(const CppSharp::CppParser::AST::MacroDefinition&) = &CppSharp::CppParser::AST::MacroDefinition::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_MacroExpansion_MacroExpansion___1__N_CppSharp_N_CppParser_N_AST_S_MacroExpansion(void* __instance, const CppSharp::CppParser::AST::MacroExpansion& _0) { ::new (__instance) CppSharp::CppParser::AST::MacroExpansion(_0); }
CppSharp::CppParser::AST::MacroExpansion& (CppSharp::CppParser::AST::MacroExpansion::*_91)(const CppSharp::CppParser::AST::MacroExpansion&) = &CppSharp::CppParser::AST::MacroExpansion::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_TranslationUnit_TranslationUnit___1__N_CppSharp_N_CppParser_N_AST_S_TranslationUnit(void* __instance, const CppSharp::CppParser::AST::TranslationUnit& _0) { ::new (__instance) CppSharp::CppParser::AST::TranslationUnit(_0); }
CppSharp::CppParser::AST::TranslationUnit& (CppSharp::CppParser::AST::TranslationUnit::*_92)(const CppSharp::CppParser::AST::TranslationUnit&) = &CppSharp::CppParser::AST::TranslationUnit::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_ASTContext_ASTContext___1__N_CppSharp_N_CppParser_N_AST_S_ASTContext(void* __instance, const CppSharp::CppParser::AST::ASTContext& _0) { ::new (__instance) CppSharp::CppParser::AST::ASTContext(_0); }
CppSharp::CppParser::AST::ASTContext& (CppSharp::CppParser::AST::ASTContext::*_93)(const CppSharp::CppParser::AST::ASTContext&) = &CppSharp::CppParser::AST::ASTContext::operator=;
CppSharp::CppParser::AST::Stmt& (CppSharp::CppParser::AST::Stmt::*_94)(CppSharp::CppParser::AST::Stmt&&) = &CppSharp::CppParser::AST::Stmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DeclStmt_DeclStmt___1__N_CppSharp_N_CppParser_N_AST_S_DeclStmt(void* __instance, const CppSharp::CppParser::AST::DeclStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::DeclStmt(_0); }
CppSharp::CppParser::AST::DeclStmt& (CppSharp::CppParser::AST::DeclStmt::*_95)(CppSharp::CppParser::AST::DeclStmt&&) = &CppSharp::CppParser::AST::DeclStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_DeclStmt__DeclStmt(CppSharp::CppParser::AST::DeclStmt*__instance) { __instance->~DeclStmt(); }
CppSharp::CppParser::AST::NullStmt& (CppSharp::CppParser::AST::NullStmt::*_96)(CppSharp::CppParser::AST::NullStmt&&) = &CppSharp::CppParser::AST::NullStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CompoundStmt_CompoundStmt___1__N_CppSharp_N_CppParser_N_AST_S_CompoundStmt(void* __instance, const CppSharp::CppParser::AST::CompoundStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::CompoundStmt(_0); }
CppSharp::CppParser::AST::CompoundStmt& (CppSharp::CppParser::AST::CompoundStmt::*_97)(CppSharp::CppParser::AST::CompoundStmt&&) = &CppSharp::CppParser::AST::CompoundStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CompoundStmt__CompoundStmt(CppSharp::CppParser::AST::CompoundStmt*__instance) { __instance->~CompoundStmt(); }
CppSharp::CppParser::AST::SwitchCase& (CppSharp::CppParser::AST::SwitchCase::*_98)(CppSharp::CppParser::AST::SwitchCase&&) = &CppSharp::CppParser::AST::SwitchCase::operator=;
CppSharp::CppParser::AST::CaseStmt& (CppSharp::CppParser::AST::CaseStmt::*_99)(CppSharp::CppParser::AST::CaseStmt&&) = &CppSharp::CppParser::AST::CaseStmt::operator=;
CppSharp::CppParser::AST::DefaultStmt& (CppSharp::CppParser::AST::DefaultStmt::*_100)(CppSharp::CppParser::AST::DefaultStmt&&) = &CppSharp::CppParser::AST::DefaultStmt::operator=;
CppSharp::CppParser::AST::LabelStmt& (CppSharp::CppParser::AST::LabelStmt::*_101)(CppSharp::CppParser::AST::LabelStmt&&) = &CppSharp::CppParser::AST::LabelStmt::operator=;
CppSharp::CppParser::AST::AttributedStmt& (CppSharp::CppParser::AST::AttributedStmt::*_102)(CppSharp::CppParser::AST::AttributedStmt&&) = &CppSharp::CppParser::AST::AttributedStmt::operator=;
CppSharp::CppParser::AST::IfStmt& (CppSharp::CppParser::AST::IfStmt::*_103)(CppSharp::CppParser::AST::IfStmt&&) = &CppSharp::CppParser::AST::IfStmt::operator=;
CppSharp::CppParser::AST::SwitchStmt& (CppSharp::CppParser::AST::SwitchStmt::*_104)(CppSharp::CppParser::AST::SwitchStmt&&) = &CppSharp::CppParser::AST::SwitchStmt::operator=;
CppSharp::CppParser::AST::WhileStmt& (CppSharp::CppParser::AST::WhileStmt::*_105)(CppSharp::CppParser::AST::WhileStmt&&) = &CppSharp::CppParser::AST::WhileStmt::operator=;
CppSharp::CppParser::AST::DoStmt& (CppSharp::CppParser::AST::DoStmt::*_106)(CppSharp::CppParser::AST::DoStmt&&) = &CppSharp::CppParser::AST::DoStmt::operator=;
CppSharp::CppParser::AST::ForStmt& (CppSharp::CppParser::AST::ForStmt::*_107)(CppSharp::CppParser::AST::ForStmt&&) = &CppSharp::CppParser::AST::ForStmt::operator=;
CppSharp::CppParser::AST::GotoStmt& (CppSharp::CppParser::AST::GotoStmt::*_108)(CppSharp::CppParser::AST::GotoStmt&&) = &CppSharp::CppParser::AST::GotoStmt::operator=;
CppSharp::CppParser::AST::IndirectGotoStmt& (CppSharp::CppParser::AST::IndirectGotoStmt::*_109)(CppSharp::CppParser::AST::IndirectGotoStmt&&) = &CppSharp::CppParser::AST::IndirectGotoStmt::operator=;
CppSharp::CppParser::AST::ContinueStmt& (CppSharp::CppParser::AST::ContinueStmt::*_110)(CppSharp::CppParser::AST::ContinueStmt&&) = &CppSharp::CppParser::AST::ContinueStmt::operator=;
CppSharp::CppParser::AST::BreakStmt& (CppSharp::CppParser::AST::BreakStmt::*_111)(CppSharp::CppParser::AST::BreakStmt&&) = &CppSharp::CppParser::AST::BreakStmt::operator=;
CppSharp::CppParser::AST::ReturnStmt& (CppSharp::CppParser::AST::ReturnStmt::*_112)(CppSharp::CppParser::AST::ReturnStmt&&) = &CppSharp::CppParser::AST::ReturnStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_AsmStmt_AsmStmt___1__N_CppSharp_N_CppParser_N_AST_S_AsmStmt(void* __instance, const CppSharp::CppParser::AST::AsmStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::AsmStmt(_0); }
CppSharp::CppParser::AST::AsmStmt& (CppSharp::CppParser::AST::AsmStmt::*_113)(CppSharp::CppParser::AST::AsmStmt&&) = &CppSharp::CppParser::AST::AsmStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_AsmStmt__AsmStmt(CppSharp::CppParser::AST::AsmStmt*__instance) { __instance->~AsmStmt(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt_S_AsmStringPiece_AsmStringPiece___1__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt_S_AsmStringPiece(void* __instance, const CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece& _0) { ::new (__instance) CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece(_0); }
CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece& (CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece::*_114)(CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece&&) = &CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt_S_AsmStringPiece__AsmStringPiece(CppSharp::CppParser::AST::GCCAsmStmt::AsmStringPiece*__instance) { __instance->~AsmStringPiece(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt_GCCAsmStmt___1__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt(void* __instance, const CppSharp::CppParser::AST::GCCAsmStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::GCCAsmStmt(_0); }
CppSharp::CppParser::AST::GCCAsmStmt& (CppSharp::CppParser::AST::GCCAsmStmt::*_115)(CppSharp::CppParser::AST::GCCAsmStmt&&) = &CppSharp::CppParser::AST::GCCAsmStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_GCCAsmStmt__GCCAsmStmt(CppSharp::CppParser::AST::GCCAsmStmt*__instance) { __instance->~GCCAsmStmt(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_MSAsmStmt_MSAsmStmt___1__N_CppSharp_N_CppParser_N_AST_S_MSAsmStmt(void* __instance, const CppSharp::CppParser::AST::MSAsmStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::MSAsmStmt(_0); }
CppSharp::CppParser::AST::MSAsmStmt& (CppSharp::CppParser::AST::MSAsmStmt::*_116)(CppSharp::CppParser::AST::MSAsmStmt&&) = &CppSharp::CppParser::AST::MSAsmStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_MSAsmStmt__MSAsmStmt(CppSharp::CppParser::AST::MSAsmStmt*__instance) { __instance->~MSAsmStmt(); }
CppSharp::CppParser::AST::SEHExceptStmt& (CppSharp::CppParser::AST::SEHExceptStmt::*_117)(CppSharp::CppParser::AST::SEHExceptStmt&&) = &CppSharp::CppParser::AST::SEHExceptStmt::operator=;
CppSharp::CppParser::AST::SEHFinallyStmt& (CppSharp::CppParser::AST::SEHFinallyStmt::*_118)(CppSharp::CppParser::AST::SEHFinallyStmt&&) = &CppSharp::CppParser::AST::SEHFinallyStmt::operator=;
CppSharp::CppParser::AST::SEHTryStmt& (CppSharp::CppParser::AST::SEHTryStmt::*_119)(CppSharp::CppParser::AST::SEHTryStmt&&) = &CppSharp::CppParser::AST::SEHTryStmt::operator=;
CppSharp::CppParser::AST::SEHLeaveStmt& (CppSharp::CppParser::AST::SEHLeaveStmt::*_120)(CppSharp::CppParser::AST::SEHLeaveStmt&&) = &CppSharp::CppParser::AST::SEHLeaveStmt::operator=;
CppSharp::CppParser::AST::CapturedStmt::Capture& (CppSharp::CppParser::AST::CapturedStmt::Capture::*_121)(CppSharp::CppParser::AST::CapturedStmt::Capture&&) = &CppSharp::CppParser::AST::CapturedStmt::Capture::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CapturedStmt_CapturedStmt___1__N_CppSharp_N_CppParser_N_AST_S_CapturedStmt(void* __instance, const CppSharp::CppParser::AST::CapturedStmt& _0) { ::new (__instance) CppSharp::CppParser::AST::CapturedStmt(_0); }
CppSharp::CppParser::AST::CapturedStmt& (CppSharp::CppParser::AST::CapturedStmt::*_122)(CppSharp::CppParser::AST::CapturedStmt&&) = &CppSharp::CppParser::AST::CapturedStmt::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CapturedStmt__CapturedStmt(CppSharp::CppParser::AST::CapturedStmt*__instance) { __instance->~CapturedStmt(); }
CppSharp::CppParser::AST::CXXCatchStmt& (CppSharp::CppParser::AST::CXXCatchStmt::*_123)(CppSharp::CppParser::AST::CXXCatchStmt&&) = &CppSharp::CppParser::AST::CXXCatchStmt::operator=;
CppSharp::CppParser::AST::CXXTryStmt& (CppSharp::CppParser::AST::CXXTryStmt::*_124)(CppSharp::CppParser::AST::CXXTryStmt&&) = &CppSharp::CppParser::AST::CXXTryStmt::operator=;
CppSharp::CppParser::AST::CXXForRangeStmt& (CppSharp::CppParser::AST::CXXForRangeStmt::*_125)(CppSharp::CppParser::AST::CXXForRangeStmt&&) = &CppSharp::CppParser::AST::CXXForRangeStmt::operator=;
CppSharp::CppParser::AST::MSDependentExistsStmt& (CppSharp::CppParser::AST::MSDependentExistsStmt::*_126)(CppSharp::CppParser::AST::MSDependentExistsStmt&&) = &CppSharp::CppParser::AST::MSDependentExistsStmt::operator=;
CppSharp::CppParser::AST::CoroutineBodyStmt::CtorArgs& (CppSharp::CppParser::AST::CoroutineBodyStmt::CtorArgs::*_127)(CppSharp::CppParser::AST::CoroutineBodyStmt::CtorArgs&&) = &CppSharp::CppParser::AST::CoroutineBodyStmt::CtorArgs::operator=;
CppSharp::CppParser::AST::CoroutineBodyStmt& (CppSharp::CppParser::AST::CoroutineBodyStmt::*_128)(CppSharp::CppParser::AST::CoroutineBodyStmt&&) = &CppSharp::CppParser::AST::CoroutineBodyStmt::operator=;
CppSharp::CppParser::AST::CoreturnStmt& (CppSharp::CppParser::AST::CoreturnStmt::*_129)(CppSharp::CppParser::AST::CoreturnStmt&&) = &CppSharp::CppParser::AST::CoreturnStmt::operator=;
CppSharp::CppParser::AST::Expr::Classification& (CppSharp::CppParser::AST::Expr::Classification::*_130)(CppSharp::CppParser::AST::Expr::Classification&&) = &CppSharp::CppParser::AST::Expr::Classification::operator=;
CppSharp::CppParser::AST::Expr& (CppSharp::CppParser::AST::Expr::*_131)(CppSharp::CppParser::AST::Expr&&) = &CppSharp::CppParser::AST::Expr::operator=;
CppSharp::CppParser::AST::FullExpr& (CppSharp::CppParser::AST::FullExpr::*_132)(CppSharp::CppParser::AST::FullExpr&&) = &CppSharp::CppParser::AST::FullExpr::operator=;
CppSharp::CppParser::AST::ConstantExpr& (CppSharp::CppParser::AST::ConstantExpr::*_133)(CppSharp::CppParser::AST::ConstantExpr&&) = &CppSharp::CppParser::AST::ConstantExpr::operator=;
CppSharp::CppParser::AST::OpaqueValueExpr& (CppSharp::CppParser::AST::OpaqueValueExpr::*_134)(CppSharp::CppParser::AST::OpaqueValueExpr&&) = &CppSharp::CppParser::AST::OpaqueValueExpr::operator=;
CppSharp::CppParser::AST::DeclRefExpr& (CppSharp::CppParser::AST::DeclRefExpr::*_135)(CppSharp::CppParser::AST::DeclRefExpr&&) = &CppSharp::CppParser::AST::DeclRefExpr::operator=;
CppSharp::CppParser::AST::IntegerLiteral& (CppSharp::CppParser::AST::IntegerLiteral::*_136)(CppSharp::CppParser::AST::IntegerLiteral&&) = &CppSharp::CppParser::AST::IntegerLiteral::operator=;
CppSharp::CppParser::AST::FixedPointLiteral& (CppSharp::CppParser::AST::FixedPointLiteral::*_137)(CppSharp::CppParser::AST::FixedPointLiteral&&) = &CppSharp::CppParser::AST::FixedPointLiteral::operator=;
CppSharp::CppParser::AST::CharacterLiteral& (CppSharp::CppParser::AST::CharacterLiteral::*_138)(CppSharp::CppParser::AST::CharacterLiteral&&) = &CppSharp::CppParser::AST::CharacterLiteral::operator=;
CppSharp::CppParser::AST::FloatingLiteral& (CppSharp::CppParser::AST::FloatingLiteral::*_139)(CppSharp::CppParser::AST::FloatingLiteral&&) = &CppSharp::CppParser::AST::FloatingLiteral::operator=;
CppSharp::CppParser::AST::ImaginaryLiteral& (CppSharp::CppParser::AST::ImaginaryLiteral::*_140)(CppSharp::CppParser::AST::ImaginaryLiteral&&) = &CppSharp::CppParser::AST::ImaginaryLiteral::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_StringLiteral_StringLiteral___1__N_CppSharp_N_CppParser_N_AST_S_StringLiteral(void* __instance, const CppSharp::CppParser::AST::StringLiteral& _0) { ::new (__instance) CppSharp::CppParser::AST::StringLiteral(_0); }
CppSharp::CppParser::AST::StringLiteral& (CppSharp::CppParser::AST::StringLiteral::*_141)(CppSharp::CppParser::AST::StringLiteral&&) = &CppSharp::CppParser::AST::StringLiteral::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_StringLiteral__StringLiteral(CppSharp::CppParser::AST::StringLiteral*__instance) { __instance->~StringLiteral(); }
CppSharp::CppParser::AST::PredefinedExpr& (CppSharp::CppParser::AST::PredefinedExpr::*_142)(CppSharp::CppParser::AST::PredefinedExpr&&) = &CppSharp::CppParser::AST::PredefinedExpr::operator=;
CppSharp::CppParser::AST::ParenExpr& (CppSharp::CppParser::AST::ParenExpr::*_143)(CppSharp::CppParser::AST::ParenExpr&&) = &CppSharp::CppParser::AST::ParenExpr::operator=;
CppSharp::CppParser::AST::UnaryOperator& (CppSharp::CppParser::AST::UnaryOperator::*_144)(CppSharp::CppParser::AST::UnaryOperator&&) = &CppSharp::CppParser::AST::UnaryOperator::operator=;
CppSharp::CppParser::AST::OffsetOfExpr& (CppSharp::CppParser::AST::OffsetOfExpr::*_145)(CppSharp::CppParser::AST::OffsetOfExpr&&) = &CppSharp::CppParser::AST::OffsetOfExpr::operator=;
CppSharp::CppParser::AST::UnaryExprOrTypeTraitExpr& (CppSharp::CppParser::AST::UnaryExprOrTypeTraitExpr::*_146)(CppSharp::CppParser::AST::UnaryExprOrTypeTraitExpr&&) = &CppSharp::CppParser::AST::UnaryExprOrTypeTraitExpr::operator=;
CppSharp::CppParser::AST::ArraySubscriptExpr& (CppSharp::CppParser::AST::ArraySubscriptExpr::*_147)(CppSharp::CppParser::AST::ArraySubscriptExpr&&) = &CppSharp::CppParser::AST::ArraySubscriptExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CallExpr_CallExpr___1__N_CppSharp_N_CppParser_N_AST_S_CallExpr(void* __instance, const CppSharp::CppParser::AST::CallExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CallExpr(_0); }
CppSharp::CppParser::AST::CallExpr& (CppSharp::CppParser::AST::CallExpr::*_148)(CppSharp::CppParser::AST::CallExpr&&) = &CppSharp::CppParser::AST::CallExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CallExpr__CallExpr(CppSharp::CppParser::AST::CallExpr*__instance) { __instance->~CallExpr(); }
CppSharp::CppParser::AST::MemberExpr& (CppSharp::CppParser::AST::MemberExpr::*_149)(CppSharp::CppParser::AST::MemberExpr&&) = &CppSharp::CppParser::AST::MemberExpr::operator=;
CppSharp::CppParser::AST::CompoundLiteralExpr& (CppSharp::CppParser::AST::CompoundLiteralExpr::*_150)(CppSharp::CppParser::AST::CompoundLiteralExpr&&) = &CppSharp::CppParser::AST::CompoundLiteralExpr::operator=;
CppSharp::CppParser::AST::CastExpr& (CppSharp::CppParser::AST::CastExpr::*_151)(CppSharp::CppParser::AST::CastExpr&&) = &CppSharp::CppParser::AST::CastExpr::operator=;
CppSharp::CppParser::AST::ImplicitCastExpr& (CppSharp::CppParser::AST::ImplicitCastExpr::*_152)(CppSharp::CppParser::AST::ImplicitCastExpr&&) = &CppSharp::CppParser::AST::ImplicitCastExpr::operator=;
CppSharp::CppParser::AST::ExplicitCastExpr& (CppSharp::CppParser::AST::ExplicitCastExpr::*_153)(CppSharp::CppParser::AST::ExplicitCastExpr&&) = &CppSharp::CppParser::AST::ExplicitCastExpr::operator=;
CppSharp::CppParser::AST::CStyleCastExpr& (CppSharp::CppParser::AST::CStyleCastExpr::*_154)(CppSharp::CppParser::AST::CStyleCastExpr&&) = &CppSharp::CppParser::AST::CStyleCastExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BinaryOperator_BinaryOperator___1__N_CppSharp_N_CppParser_N_AST_S_BinaryOperator(void* __instance, const CppSharp::CppParser::AST::BinaryOperator& _0) { ::new (__instance) CppSharp::CppParser::AST::BinaryOperator(_0); }
CppSharp::CppParser::AST::BinaryOperator& (CppSharp::CppParser::AST::BinaryOperator::*_155)(CppSharp::CppParser::AST::BinaryOperator&&) = &CppSharp::CppParser::AST::BinaryOperator::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_BinaryOperator__BinaryOperator(CppSharp::CppParser::AST::BinaryOperator*__instance) { __instance->~BinaryOperator(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CompoundAssignOperator_CompoundAssignOperator___1__N_CppSharp_N_CppParser_N_AST_S_CompoundAssignOperator(void* __instance, const CppSharp::CppParser::AST::CompoundAssignOperator& _0) { ::new (__instance) CppSharp::CppParser::AST::CompoundAssignOperator(_0); }
CppSharp::CppParser::AST::CompoundAssignOperator& (CppSharp::CppParser::AST::CompoundAssignOperator::*_156)(CppSharp::CppParser::AST::CompoundAssignOperator&&) = &CppSharp::CppParser::AST::CompoundAssignOperator::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CompoundAssignOperator__CompoundAssignOperator(CppSharp::CppParser::AST::CompoundAssignOperator*__instance) { __instance->~CompoundAssignOperator(); }
CppSharp::CppParser::AST::AbstractConditionalOperator& (CppSharp::CppParser::AST::AbstractConditionalOperator::*_157)(CppSharp::CppParser::AST::AbstractConditionalOperator&&) = &CppSharp::CppParser::AST::AbstractConditionalOperator::operator=;
CppSharp::CppParser::AST::ConditionalOperator& (CppSharp::CppParser::AST::ConditionalOperator::*_158)(CppSharp::CppParser::AST::ConditionalOperator&&) = &CppSharp::CppParser::AST::ConditionalOperator::operator=;
CppSharp::CppParser::AST::BinaryConditionalOperator& (CppSharp::CppParser::AST::BinaryConditionalOperator::*_159)(CppSharp::CppParser::AST::BinaryConditionalOperator&&) = &CppSharp::CppParser::AST::BinaryConditionalOperator::operator=;
CppSharp::CppParser::AST::AddrLabelExpr& (CppSharp::CppParser::AST::AddrLabelExpr::*_160)(CppSharp::CppParser::AST::AddrLabelExpr&&) = &CppSharp::CppParser::AST::AddrLabelExpr::operator=;
CppSharp::CppParser::AST::StmtExpr& (CppSharp::CppParser::AST::StmtExpr::*_161)(CppSharp::CppParser::AST::StmtExpr&&) = &CppSharp::CppParser::AST::StmtExpr::operator=;
CppSharp::CppParser::AST::ShuffleVectorExpr& (CppSharp::CppParser::AST::ShuffleVectorExpr::*_162)(CppSharp::CppParser::AST::ShuffleVectorExpr&&) = &CppSharp::CppParser::AST::ShuffleVectorExpr::operator=;
CppSharp::CppParser::AST::ConvertVectorExpr& (CppSharp::CppParser::AST::ConvertVectorExpr::*_163)(CppSharp::CppParser::AST::ConvertVectorExpr&&) = &CppSharp::CppParser::AST::ConvertVectorExpr::operator=;
CppSharp::CppParser::AST::ChooseExpr& (CppSharp::CppParser::AST::ChooseExpr::*_164)(CppSharp::CppParser::AST::ChooseExpr&&) = &CppSharp::CppParser::AST::ChooseExpr::operator=;
CppSharp::CppParser::AST::GNUNullExpr& (CppSharp::CppParser::AST::GNUNullExpr::*_165)(CppSharp::CppParser::AST::GNUNullExpr&&) = &CppSharp::CppParser::AST::GNUNullExpr::operator=;
CppSharp::CppParser::AST::VAArgExpr& (CppSharp::CppParser::AST::VAArgExpr::*_166)(CppSharp::CppParser::AST::VAArgExpr&&) = &CppSharp::CppParser::AST::VAArgExpr::operator=;
CppSharp::CppParser::AST::InitListExpr& (CppSharp::CppParser::AST::InitListExpr::*_167)(CppSharp::CppParser::AST::InitListExpr&&) = &CppSharp::CppParser::AST::InitListExpr::operator=;
CppSharp::CppParser::AST::DesignatedInitExpr::Designator& (CppSharp::CppParser::AST::DesignatedInitExpr::Designator::*_168)(CppSharp::CppParser::AST::DesignatedInitExpr::Designator&&) = &CppSharp::CppParser::AST::DesignatedInitExpr::Designator::operator=;
CppSharp::CppParser::AST::DesignatedInitExpr::FieldDesignator& (CppSharp::CppParser::AST::DesignatedInitExpr::FieldDesignator::*_169)(CppSharp::CppParser::AST::DesignatedInitExpr::FieldDesignator&&) = &CppSharp::CppParser::AST::DesignatedInitExpr::FieldDesignator::operator=;
CppSharp::CppParser::AST::DesignatedInitExpr::ArrayOrRangeDesignator& (CppSharp::CppParser::AST::DesignatedInitExpr::ArrayOrRangeDesignator::*_170)(CppSharp::CppParser::AST::DesignatedInitExpr::ArrayOrRangeDesignator&&) = &CppSharp::CppParser::AST::DesignatedInitExpr::ArrayOrRangeDesignator::operator=;
CppSharp::CppParser::AST::DesignatedInitExpr& (CppSharp::CppParser::AST::DesignatedInitExpr::*_171)(CppSharp::CppParser::AST::DesignatedInitExpr&&) = &CppSharp::CppParser::AST::DesignatedInitExpr::operator=;
CppSharp::CppParser::AST::NoInitExpr& (CppSharp::CppParser::AST::NoInitExpr::*_172)(CppSharp::CppParser::AST::NoInitExpr&&) = &CppSharp::CppParser::AST::NoInitExpr::operator=;
CppSharp::CppParser::AST::DesignatedInitUpdateExpr& (CppSharp::CppParser::AST::DesignatedInitUpdateExpr::*_173)(CppSharp::CppParser::AST::DesignatedInitUpdateExpr&&) = &CppSharp::CppParser::AST::DesignatedInitUpdateExpr::operator=;
CppSharp::CppParser::AST::ArrayInitLoopExpr& (CppSharp::CppParser::AST::ArrayInitLoopExpr::*_174)(CppSharp::CppParser::AST::ArrayInitLoopExpr&&) = &CppSharp::CppParser::AST::ArrayInitLoopExpr::operator=;
CppSharp::CppParser::AST::ArrayInitIndexExpr& (CppSharp::CppParser::AST::ArrayInitIndexExpr::*_175)(CppSharp::CppParser::AST::ArrayInitIndexExpr&&) = &CppSharp::CppParser::AST::ArrayInitIndexExpr::operator=;
CppSharp::CppParser::AST::ImplicitValueInitExpr& (CppSharp::CppParser::AST::ImplicitValueInitExpr::*_176)(CppSharp::CppParser::AST::ImplicitValueInitExpr&&) = &CppSharp::CppParser::AST::ImplicitValueInitExpr::operator=;
CppSharp::CppParser::AST::ParenListExpr& (CppSharp::CppParser::AST::ParenListExpr::*_177)(CppSharp::CppParser::AST::ParenListExpr&&) = &CppSharp::CppParser::AST::ParenListExpr::operator=;
CppSharp::CppParser::AST::GenericSelectionExpr& (CppSharp::CppParser::AST::GenericSelectionExpr::*_178)(CppSharp::CppParser::AST::GenericSelectionExpr&&) = &CppSharp::CppParser::AST::GenericSelectionExpr::operator=;
CppSharp::CppParser::AST::ExtVectorElementExpr& (CppSharp::CppParser::AST::ExtVectorElementExpr::*_179)(CppSharp::CppParser::AST::ExtVectorElementExpr&&) = &CppSharp::CppParser::AST::ExtVectorElementExpr::operator=;
CppSharp::CppParser::AST::BlockExpr& (CppSharp::CppParser::AST::BlockExpr::*_180)(CppSharp::CppParser::AST::BlockExpr&&) = &CppSharp::CppParser::AST::BlockExpr::operator=;
CppSharp::CppParser::AST::AsTypeExpr& (CppSharp::CppParser::AST::AsTypeExpr::*_181)(CppSharp::CppParser::AST::AsTypeExpr&&) = &CppSharp::CppParser::AST::AsTypeExpr::operator=;
CppSharp::CppParser::AST::PseudoObjectExpr& (CppSharp::CppParser::AST::PseudoObjectExpr::*_182)(CppSharp::CppParser::AST::PseudoObjectExpr&&) = &CppSharp::CppParser::AST::PseudoObjectExpr::operator=;
CppSharp::CppParser::AST::AtomicExpr& (CppSharp::CppParser::AST::AtomicExpr::*_183)(CppSharp::CppParser::AST::AtomicExpr&&) = &CppSharp::CppParser::AST::AtomicExpr::operator=;
CppSharp::CppParser::AST::TypoExpr& (CppSharp::CppParser::AST::TypoExpr::*_184)(CppSharp::CppParser::AST::TypoExpr&&) = &CppSharp::CppParser::AST::TypoExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXOperatorCallExpr_CXXOperatorCallExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXOperatorCallExpr(void* __instance, const CppSharp::CppParser::AST::CXXOperatorCallExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXOperatorCallExpr(_0); }
CppSharp::CppParser::AST::CXXOperatorCallExpr& (CppSharp::CppParser::AST::CXXOperatorCallExpr::*_185)(CppSharp::CppParser::AST::CXXOperatorCallExpr&&) = &CppSharp::CppParser::AST::CXXOperatorCallExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXOperatorCallExpr__CXXOperatorCallExpr(CppSharp::CppParser::AST::CXXOperatorCallExpr*__instance) { __instance->~CXXOperatorCallExpr(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXMemberCallExpr_CXXMemberCallExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXMemberCallExpr(void* __instance, const CppSharp::CppParser::AST::CXXMemberCallExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXMemberCallExpr(_0); }
CppSharp::CppParser::AST::CXXMemberCallExpr& (CppSharp::CppParser::AST::CXXMemberCallExpr::*_186)(CppSharp::CppParser::AST::CXXMemberCallExpr&&) = &CppSharp::CppParser::AST::CXXMemberCallExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXMemberCallExpr__CXXMemberCallExpr(CppSharp::CppParser::AST::CXXMemberCallExpr*__instance) { __instance->~CXXMemberCallExpr(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CUDAKernelCallExpr_CUDAKernelCallExpr___1__N_CppSharp_N_CppParser_N_AST_S_CUDAKernelCallExpr(void* __instance, const CppSharp::CppParser::AST::CUDAKernelCallExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CUDAKernelCallExpr(_0); }
CppSharp::CppParser::AST::CUDAKernelCallExpr& (CppSharp::CppParser::AST::CUDAKernelCallExpr::*_187)(CppSharp::CppParser::AST::CUDAKernelCallExpr&&) = &CppSharp::CppParser::AST::CUDAKernelCallExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CUDAKernelCallExpr__CUDAKernelCallExpr(CppSharp::CppParser::AST::CUDAKernelCallExpr*__instance) { __instance->~CUDAKernelCallExpr(); }
CppSharp::CppParser::AST::CXXNamedCastExpr& (CppSharp::CppParser::AST::CXXNamedCastExpr::*_188)(CppSharp::CppParser::AST::CXXNamedCastExpr&&) = &CppSharp::CppParser::AST::CXXNamedCastExpr::operator=;
CppSharp::CppParser::AST::CXXStaticCastExpr& (CppSharp::CppParser::AST::CXXStaticCastExpr::*_189)(CppSharp::CppParser::AST::CXXStaticCastExpr&&) = &CppSharp::CppParser::AST::CXXStaticCastExpr::operator=;
CppSharp::CppParser::AST::CXXDynamicCastExpr& (CppSharp::CppParser::AST::CXXDynamicCastExpr::*_190)(CppSharp::CppParser::AST::CXXDynamicCastExpr&&) = &CppSharp::CppParser::AST::CXXDynamicCastExpr::operator=;
CppSharp::CppParser::AST::CXXReinterpretCastExpr& (CppSharp::CppParser::AST::CXXReinterpretCastExpr::*_191)(CppSharp::CppParser::AST::CXXReinterpretCastExpr&&) = &CppSharp::CppParser::AST::CXXReinterpretCastExpr::operator=;
CppSharp::CppParser::AST::CXXConstCastExpr& (CppSharp::CppParser::AST::CXXConstCastExpr::*_192)(CppSharp::CppParser::AST::CXXConstCastExpr&&) = &CppSharp::CppParser::AST::CXXConstCastExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_UserDefinedLiteral_UserDefinedLiteral___1__N_CppSharp_N_CppParser_N_AST_S_UserDefinedLiteral(void* __instance, const CppSharp::CppParser::AST::UserDefinedLiteral& _0) { ::new (__instance) CppSharp::CppParser::AST::UserDefinedLiteral(_0); }
CppSharp::CppParser::AST::UserDefinedLiteral& (CppSharp::CppParser::AST::UserDefinedLiteral::*_193)(CppSharp::CppParser::AST::UserDefinedLiteral&&) = &CppSharp::CppParser::AST::UserDefinedLiteral::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_UserDefinedLiteral__UserDefinedLiteral(CppSharp::CppParser::AST::UserDefinedLiteral*__instance) { __instance->~UserDefinedLiteral(); }
CppSharp::CppParser::AST::CXXBoolLiteralExpr& (CppSharp::CppParser::AST::CXXBoolLiteralExpr::*_194)(CppSharp::CppParser::AST::CXXBoolLiteralExpr&&) = &CppSharp::CppParser::AST::CXXBoolLiteralExpr::operator=;
CppSharp::CppParser::AST::CXXNullPtrLiteralExpr& (CppSharp::CppParser::AST::CXXNullPtrLiteralExpr::*_195)(CppSharp::CppParser::AST::CXXNullPtrLiteralExpr&&) = &CppSharp::CppParser::AST::CXXNullPtrLiteralExpr::operator=;
CppSharp::CppParser::AST::CXXStdInitializerListExpr& (CppSharp::CppParser::AST::CXXStdInitializerListExpr::*_196)(CppSharp::CppParser::AST::CXXStdInitializerListExpr&&) = &CppSharp::CppParser::AST::CXXStdInitializerListExpr::operator=;
CppSharp::CppParser::AST::CXXTypeidExpr& (CppSharp::CppParser::AST::CXXTypeidExpr::*_197)(CppSharp::CppParser::AST::CXXTypeidExpr&&) = &CppSharp::CppParser::AST::CXXTypeidExpr::operator=;
CppSharp::CppParser::AST::MSPropertyRefExpr& (CppSharp::CppParser::AST::MSPropertyRefExpr::*_198)(CppSharp::CppParser::AST::MSPropertyRefExpr&&) = &CppSharp::CppParser::AST::MSPropertyRefExpr::operator=;
CppSharp::CppParser::AST::MSPropertySubscriptExpr& (CppSharp::CppParser::AST::MSPropertySubscriptExpr::*_199)(CppSharp::CppParser::AST::MSPropertySubscriptExpr&&) = &CppSharp::CppParser::AST::MSPropertySubscriptExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXUuidofExpr_CXXUuidofExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXUuidofExpr(void* __instance, const CppSharp::CppParser::AST::CXXUuidofExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXUuidofExpr(_0); }
CppSharp::CppParser::AST::CXXUuidofExpr& (CppSharp::CppParser::AST::CXXUuidofExpr::*_200)(CppSharp::CppParser::AST::CXXUuidofExpr&&) = &CppSharp::CppParser::AST::CXXUuidofExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXUuidofExpr__CXXUuidofExpr(CppSharp::CppParser::AST::CXXUuidofExpr*__instance) { __instance->~CXXUuidofExpr(); }
CppSharp::CppParser::AST::CXXThisExpr& (CppSharp::CppParser::AST::CXXThisExpr::*_201)(CppSharp::CppParser::AST::CXXThisExpr&&) = &CppSharp::CppParser::AST::CXXThisExpr::operator=;
CppSharp::CppParser::AST::CXXThrowExpr& (CppSharp::CppParser::AST::CXXThrowExpr::*_202)(CppSharp::CppParser::AST::CXXThrowExpr&&) = &CppSharp::CppParser::AST::CXXThrowExpr::operator=;
CppSharp::CppParser::AST::CXXDefaultArgExpr& (CppSharp::CppParser::AST::CXXDefaultArgExpr::*_203)(CppSharp::CppParser::AST::CXXDefaultArgExpr&&) = &CppSharp::CppParser::AST::CXXDefaultArgExpr::operator=;
CppSharp::CppParser::AST::CXXDefaultInitExpr& (CppSharp::CppParser::AST::CXXDefaultInitExpr::*_204)(CppSharp::CppParser::AST::CXXDefaultInitExpr&&) = &CppSharp::CppParser::AST::CXXDefaultInitExpr::operator=;
CppSharp::CppParser::AST::CXXBindTemporaryExpr& (CppSharp::CppParser::AST::CXXBindTemporaryExpr::*_205)(CppSharp::CppParser::AST::CXXBindTemporaryExpr&&) = &CppSharp::CppParser::AST::CXXBindTemporaryExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXConstructExpr_CXXConstructExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXConstructExpr(void* __instance, const CppSharp::CppParser::AST::CXXConstructExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXConstructExpr(_0); }
CppSharp::CppParser::AST::CXXConstructExpr& (CppSharp::CppParser::AST::CXXConstructExpr::*_206)(CppSharp::CppParser::AST::CXXConstructExpr&&) = &CppSharp::CppParser::AST::CXXConstructExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXConstructExpr__CXXConstructExpr(CppSharp::CppParser::AST::CXXConstructExpr*__instance) { __instance->~CXXConstructExpr(); }
CppSharp::CppParser::AST::CXXInheritedCtorInitExpr& (CppSharp::CppParser::AST::CXXInheritedCtorInitExpr::*_207)(CppSharp::CppParser::AST::CXXInheritedCtorInitExpr&&) = &CppSharp::CppParser::AST::CXXInheritedCtorInitExpr::operator=;
CppSharp::CppParser::AST::CXXFunctionalCastExpr& (CppSharp::CppParser::AST::CXXFunctionalCastExpr::*_208)(CppSharp::CppParser::AST::CXXFunctionalCastExpr&&) = &CppSharp::CppParser::AST::CXXFunctionalCastExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXTemporaryObjectExpr_CXXTemporaryObjectExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXTemporaryObjectExpr(void* __instance, const CppSharp::CppParser::AST::CXXTemporaryObjectExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXTemporaryObjectExpr(_0); }
CppSharp::CppParser::AST::CXXTemporaryObjectExpr& (CppSharp::CppParser::AST::CXXTemporaryObjectExpr::*_209)(CppSharp::CppParser::AST::CXXTemporaryObjectExpr&&) = &CppSharp::CppParser::AST::CXXTemporaryObjectExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXTemporaryObjectExpr__CXXTemporaryObjectExpr(CppSharp::CppParser::AST::CXXTemporaryObjectExpr*__instance) { __instance->~CXXTemporaryObjectExpr(); }
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_LambdaExpr_LambdaExpr___1__N_CppSharp_N_CppParser_N_AST_S_LambdaExpr(void* __instance, const CppSharp::CppParser::AST::LambdaExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::LambdaExpr(_0); }
CppSharp::CppParser::AST::LambdaExpr& (CppSharp::CppParser::AST::LambdaExpr::*_210)(CppSharp::CppParser::AST::LambdaExpr&&) = &CppSharp::CppParser::AST::LambdaExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_LambdaExpr__LambdaExpr(CppSharp::CppParser::AST::LambdaExpr*__instance) { __instance->~LambdaExpr(); }
CppSharp::CppParser::AST::CXXScalarValueInitExpr& (CppSharp::CppParser::AST::CXXScalarValueInitExpr::*_211)(CppSharp::CppParser::AST::CXXScalarValueInitExpr&&) = &CppSharp::CppParser::AST::CXXScalarValueInitExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXNewExpr_CXXNewExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXNewExpr(void* __instance, const CppSharp::CppParser::AST::CXXNewExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXNewExpr(_0); }
CppSharp::CppParser::AST::CXXNewExpr& (CppSharp::CppParser::AST::CXXNewExpr::*_212)(CppSharp::CppParser::AST::CXXNewExpr&&) = &CppSharp::CppParser::AST::CXXNewExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXNewExpr__CXXNewExpr(CppSharp::CppParser::AST::CXXNewExpr*__instance) { __instance->~CXXNewExpr(); }
CppSharp::CppParser::AST::CXXDeleteExpr& (CppSharp::CppParser::AST::CXXDeleteExpr::*_213)(CppSharp::CppParser::AST::CXXDeleteExpr&&) = &CppSharp::CppParser::AST::CXXDeleteExpr::operator=;
CppSharp::CppParser::AST::CXXPseudoDestructorExpr& (CppSharp::CppParser::AST::CXXPseudoDestructorExpr::*_214)(CppSharp::CppParser::AST::CXXPseudoDestructorExpr&&) = &CppSharp::CppParser::AST::CXXPseudoDestructorExpr::operator=;
CppSharp::CppParser::AST::TypeTraitExpr& (CppSharp::CppParser::AST::TypeTraitExpr::*_215)(CppSharp::CppParser::AST::TypeTraitExpr&&) = &CppSharp::CppParser::AST::TypeTraitExpr::operator=;
CppSharp::CppParser::AST::ArrayTypeTraitExpr& (CppSharp::CppParser::AST::ArrayTypeTraitExpr::*_216)(CppSharp::CppParser::AST::ArrayTypeTraitExpr&&) = &CppSharp::CppParser::AST::ArrayTypeTraitExpr::operator=;
CppSharp::CppParser::AST::ExpressionTraitExpr& (CppSharp::CppParser::AST::ExpressionTraitExpr::*_217)(CppSharp::CppParser::AST::ExpressionTraitExpr&&) = &CppSharp::CppParser::AST::ExpressionTraitExpr::operator=;
CppSharp::CppParser::AST::OverloadExpr::FindResult& (CppSharp::CppParser::AST::OverloadExpr::FindResult::*_218)(CppSharp::CppParser::AST::OverloadExpr::FindResult&&) = &CppSharp::CppParser::AST::OverloadExpr::FindResult::operator=;
CppSharp::CppParser::AST::OverloadExpr& (CppSharp::CppParser::AST::OverloadExpr::*_219)(CppSharp::CppParser::AST::OverloadExpr&&) = &CppSharp::CppParser::AST::OverloadExpr::operator=;
CppSharp::CppParser::AST::UnresolvedLookupExpr& (CppSharp::CppParser::AST::UnresolvedLookupExpr::*_220)(CppSharp::CppParser::AST::UnresolvedLookupExpr&&) = &CppSharp::CppParser::AST::UnresolvedLookupExpr::operator=;
CppSharp::CppParser::AST::DependentScopeDeclRefExpr& (CppSharp::CppParser::AST::DependentScopeDeclRefExpr::*_221)(CppSharp::CppParser::AST::DependentScopeDeclRefExpr&&) = &CppSharp::CppParser::AST::DependentScopeDeclRefExpr::operator=;
CppSharp::CppParser::AST::ExprWithCleanups& (CppSharp::CppParser::AST::ExprWithCleanups::*_222)(CppSharp::CppParser::AST::ExprWithCleanups&&) = &CppSharp::CppParser::AST::ExprWithCleanups::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXUnresolvedConstructExpr_CXXUnresolvedConstructExpr___1__N_CppSharp_N_CppParser_N_AST_S_CXXUnresolvedConstructExpr(void* __instance, const CppSharp::CppParser::AST::CXXUnresolvedConstructExpr& _0) { ::new (__instance) CppSharp::CppParser::AST::CXXUnresolvedConstructExpr(_0); }
CppSharp::CppParser::AST::CXXUnresolvedConstructExpr& (CppSharp::CppParser::AST::CXXUnresolvedConstructExpr::*_223)(CppSharp::CppParser::AST::CXXUnresolvedConstructExpr&&) = &CppSharp::CppParser::AST::CXXUnresolvedConstructExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_N_AST_S_CXXUnresolvedConstructExpr__CXXUnresolvedConstructExpr(CppSharp::CppParser::AST::CXXUnresolvedConstructExpr*__instance) { __instance->~CXXUnresolvedConstructExpr(); }
CppSharp::CppParser::AST::CXXDependentScopeMemberExpr& (CppSharp::CppParser::AST::CXXDependentScopeMemberExpr::*_224)(CppSharp::CppParser::AST::CXXDependentScopeMemberExpr&&) = &CppSharp::CppParser::AST::CXXDependentScopeMemberExpr::operator=;
CppSharp::CppParser::AST::UnresolvedMemberExpr& (CppSharp::CppParser::AST::UnresolvedMemberExpr::*_225)(CppSharp::CppParser::AST::UnresolvedMemberExpr&&) = &CppSharp::CppParser::AST::UnresolvedMemberExpr::operator=;
CppSharp::CppParser::AST::CXXNoexceptExpr& (CppSharp::CppParser::AST::CXXNoexceptExpr::*_226)(CppSharp::CppParser::AST::CXXNoexceptExpr&&) = &CppSharp::CppParser::AST::CXXNoexceptExpr::operator=;
CppSharp::CppParser::AST::PackExpansionExpr& (CppSharp::CppParser::AST::PackExpansionExpr::*_227)(CppSharp::CppParser::AST::PackExpansionExpr&&) = &CppSharp::CppParser::AST::PackExpansionExpr::operator=;
CppSharp::CppParser::AST::SizeOfPackExpr& (CppSharp::CppParser::AST::SizeOfPackExpr::*_228)(CppSharp::CppParser::AST::SizeOfPackExpr&&) = &CppSharp::CppParser::AST::SizeOfPackExpr::operator=;
CppSharp::CppParser::AST::SubstNonTypeTemplateParmExpr& (CppSharp::CppParser::AST::SubstNonTypeTemplateParmExpr::*_229)(CppSharp::CppParser::AST::SubstNonTypeTemplateParmExpr&&) = &CppSharp::CppParser::AST::SubstNonTypeTemplateParmExpr::operator=;
CppSharp::CppParser::AST::SubstNonTypeTemplateParmPackExpr& (CppSharp::CppParser::AST::SubstNonTypeTemplateParmPackExpr::*_230)(CppSharp::CppParser::AST::SubstNonTypeTemplateParmPackExpr&&) = &CppSharp::CppParser::AST::SubstNonTypeTemplateParmPackExpr::operator=;
CppSharp::CppParser::AST::FunctionParmPackExpr& (CppSharp::CppParser::AST::FunctionParmPackExpr::*_231)(CppSharp::CppParser::AST::FunctionParmPackExpr&&) = &CppSharp::CppParser::AST::FunctionParmPackExpr::operator=;
CppSharp::CppParser::AST::MaterializeTemporaryExpr::ExtraState& (CppSharp::CppParser::AST::MaterializeTemporaryExpr::ExtraState::*_232)(CppSharp::CppParser::AST::MaterializeTemporaryExpr::ExtraState&&) = &CppSharp::CppParser::AST::MaterializeTemporaryExpr::ExtraState::operator=;
CppSharp::CppParser::AST::MaterializeTemporaryExpr& (CppSharp::CppParser::AST::MaterializeTemporaryExpr::*_233)(CppSharp::CppParser::AST::MaterializeTemporaryExpr&&) = &CppSharp::CppParser::AST::MaterializeTemporaryExpr::operator=;
CppSharp::CppParser::AST::CXXFoldExpr& (CppSharp::CppParser::AST::CXXFoldExpr::*_234)(CppSharp::CppParser::AST::CXXFoldExpr&&) = &CppSharp::CppParser::AST::CXXFoldExpr::operator=;
CppSharp::CppParser::AST::CoroutineSuspendExpr& (CppSharp::CppParser::AST::CoroutineSuspendExpr::*_235)(CppSharp::CppParser::AST::CoroutineSuspendExpr&&) = &CppSharp::CppParser::AST::CoroutineSuspendExpr::operator=;
CppSharp::CppParser::AST::CoawaitExpr& (CppSharp::CppParser::AST::CoawaitExpr::*_236)(CppSharp::CppParser::AST::CoawaitExpr&&) = &CppSharp::CppParser::AST::CoawaitExpr::operator=;
CppSharp::CppParser::AST::DependentCoawaitExpr& (CppSharp::CppParser::AST::DependentCoawaitExpr::*_237)(CppSharp::CppParser::AST::DependentCoawaitExpr&&) = &CppSharp::CppParser::AST::DependentCoawaitExpr::operator=;
CppSharp::CppParser::AST::CoyieldExpr& (CppSharp::CppParser::AST::CoyieldExpr::*_238)(CppSharp::CppParser::AST::CoyieldExpr&&) = &CppSharp::CppParser::AST::CoyieldExpr::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_S_ParserTargetInfo_ParserTargetInfo___1__N_CppSharp_N_CppParser_S_ParserTargetInfo(void* __instance, const CppSharp::CppParser::ParserTargetInfo& _0) { ::new (__instance) CppSharp::CppParser::ParserTargetInfo(_0); }
CppSharp::CppParser::ParserTargetInfo& (CppSharp::CppParser::ParserTargetInfo::*_239)(const CppSharp::CppParser::ParserTargetInfo&) = &CppSharp::CppParser::ParserTargetInfo::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_S_CppParserOptions_CppParserOptions___1__N_CppSharp_N_CppParser_S_CppParserOptions(void* __instance, const CppSharp::CppParser::CppParserOptions& _0) { ::new (__instance) CppSharp::CppParser::CppParserOptions(_0); }
CppSharp::CppParser::CppParserOptions& (CppSharp::CppParser::CppParserOptions::*_240)(const CppSharp::CppParser::CppParserOptions&) = &CppSharp::CppParser::CppParserOptions::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_S_LinkerOptions_LinkerOptions___1__N_CppSharp_N_CppParser_S_LinkerOptions(void* __instance, const CppSharp::CppParser::LinkerOptions& _0) { ::new (__instance) CppSharp::CppParser::LinkerOptions(_0); }
CppSharp::CppParser::LinkerOptions& (CppSharp::CppParser::LinkerOptions::*_241)(const CppSharp::CppParser::LinkerOptions&) = &CppSharp::CppParser::LinkerOptions::operator=;
CppSharp::CppParser::ParserDiagnostic& (CppSharp::CppParser::ParserDiagnostic::*_242)(const CppSharp::CppParser::ParserDiagnostic&) = &CppSharp::CppParser::ParserDiagnostic::operator=;
extern "C" __declspec(dllexport) void c__N_CppSharp_N_CppParser_S_ParserDiagnostic__ParserDiagnostic(CppSharp::CppParser::ParserDiagnostic*__instance) { __instance->~ParserDiagnostic(); }
CppSharp::CppParser::ParserResult& (CppSharp::CppParser::ParserResult::*_243)(const CppSharp::CppParser::ParserResult&) = &CppSharp::CppParser::ParserResult::operator=;
CppSharp::CppParser::ClangParser& (CppSharp::CppParser::ClangParser::*_244)(CppSharp::CppParser::ClangParser&&) = &CppSharp::CppParser::ClangParser::operator=;
